export const umaDetailSchema = {
  type: 'object',
  properties: {
    id: { type: 'number' },
    name: { type: 'string' },
    subtitle: { type: 'string' },
    apt_turf: { type: 'string' },
    apt_dirt: { type: 'string' },
    apt_short: { type: 'string' },
    apt_mile: { type: 'string' },
    apt_medium: { type: 'string' },
    apt_long: { type: 'string' },
    apt_front: { type: 'string' },
    apt_pace: { type: 'string' },
    apt_late: { type: 'string' },
    apt_end: { type: 'string' },
    growth_speed: { type: 'number' },
    growth_stamina: { type: 'number' },
    growth_power: { type: 'number' },
    growth_guts: { type: 'number' },
    growth_wit: { type: 'number' },
    release_date: { type: 'string' },
    is_predicted_date: { type: 'boolean' },
    skills: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'number' },
          name: { type: 'string' },
          category: { type: 'string' },
          rarity: { type: 'string' },
          sp_cost: { type: 'number' },
          acquisition: { type: 'string' },
          evolved_from: { type: ['number', 'null'] },
        },
        required: ['id', 'name', 'category', 'rarity', 'sp_cost', 'acquisition', 'evolved_from'],
        additionalProperties: false,
      },
    },
  },
  required: [
    'id',
    'name',
    'subtitle',
    'apt_turf',
    'apt_dirt',
    'apt_short',
    'apt_mile',
    'apt_medium',
    'apt_long',
    'apt_front',
    'apt_pace',
    'apt_late',
    'apt_end',
    'growth_speed',
    'growth_stamina',
    'growth_power',
    'growth_guts',
    'growth_wit',
    'release_date',
    'is_predicted_date',
    'skills',
  ],
  additionalProperties: false,
};
