export const umaSummarySchema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      name: { type: 'string' },
      subtitle: { type: 'string' },
      apt_turf: { type: 'string' },
      apt_dirt: { type: 'string' },
      apt_short: { type: 'string' },
      apt_mile: { type: 'string' },
      apt_medium: { type: 'string' },
      apt_long: { type: 'string' },
      apt_front: { type: 'string' },
      apt_pace: { type: 'string' },
      apt_late: { type: 'string' },
      apt_end: { type: 'string' },
    },
    required: [
      'id',
      'name',
      'subtitle',
      'apt_turf',
      'apt_dirt',
      'apt_short',
      'apt_mile',
      'apt_medium',
      'apt_long',
      'apt_front',
      'apt_pace',
      'apt_late',
      'apt_end',
    ],
    additionalProperties: false,
  },
};
